pipeline {
    agent any

    stages {
        stage('Clonar') {
            steps {
                git 'https://github.com/tatiana263/Calc.git'
            }
        }

        stage('Compilar') {
            steps {
                sh 'mvn compile'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
    }
}
